(function(e,q,z){function w(){"undefined"===typeof e.XMLHttpRequest&&(e.XMLHttpRequest=function(){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(d){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(k){}throw Error("This browser does not support XMLHttpRequest.");});var a=new e.XMLHttpRequest,f=[],d=[],b=[],c=0,t=0,g=function(){var d=new e.Function;"onreadystatechange"in a&&(a.onreadystatechange=d);"onload"in a&&(a.onload=
d);"onerror"in a&&(a.ontimeout=a.onload=d)},n=function(){4!=t&&(g(),a.abort())},h=function(d,b){for(b=0;b<d.length;b++)d[b](a)};a._abort=a.abort;a._open=a.open;a.abort=function(){c=1;a._abort()};a.open=function(d,b,k,c,g){a._open(d,b,"undefined"==typeof k?!0:k,c?c:null,g?g:null);a.setRequestHeader("X-Requested-With","XMLHttpRequest")};a.process=function(d,b,k){a.open(b?b:"GET",d);a.send("undefined"==k?null:k)};a.show_loading=function(){var a=p("#loading-layer");try{a&&(a.style.display="block",a.style.position=
"absolute",a.style.left=parseInt((e.innerWidth-a.offsetWidth)/2+e.scrollX)+"px",a.style.top=parseInt((e.innerHeight-a.offsetHeight)/2+e.scrollY)+"px")}catch(d){}};a.hide_loading=function(){try{p("#loading-layer").style.display="none"}catch(a){}};e.document.namespaces&&e.attachEvent("onunload",n);"onreadystatechange"in a&&(a.onreadystatechange=function(){c?t=0:(t!=a.readyState&&4==a.readyState&&(g(),e.document.namespaces&&e.detachEvent("onunload",n),200==a.status?h(f):h(d),h(b)),t=a.readyState)});
"onload"in a&&(a.onload=function(){a.status=200;a.state=4;h(f);h(b);e.document.namespaces&&e.detachEvent("onunload",n)});"onerror"in a&&(a.onerror=a.ontimeout=function(){a.status=0;a.state=4;h(d);h(b);e.document.namespaces&&e.detachEvent("onunload",n)});a.done=function(d){"function"===typeof d&&(f.push(d),4==a.state&&200==a.status&&d(a));return a};a.fail=function(b){"function"===typeof b&&(d.push(b),4==a.state&&200!=a.status&&b(a));return a};a.complete=function(d){"function"===typeof d&&(b.push(d),
4==a.state&&d(a));return a};return a}(function(a){function f(){return!1}function d(){return!0}function b(b){b||a.event;if(b[c])return b;b[c]=1;b[c+e]=b[e];b[c+g]=b[g];b[n]=f;b[h]=f;b[e]=function(){this[n]=d;if(this[c+e])this[c+e]();else this.returnValue=!1};b[g]=function(){this[h]=d;if(this[c+g])this[c+g]();else this.cancelBubble=!0};b.target||(b.target=b.srcElement||q);3===b.target.nodeType&&(b.target=b.target.parentNode);return b}var c="isFixed",e="preventDefault",g="stopPropagation",n="isDefaultPrevented",
h="isPropagationStopped",m=0;Array.prototype.indexOf||(Array.prototype.indexOf=function(b,a){a||(a=0);for(var d=a;d<this.length;d++)if(this[d]==b)return d;return-1});if(!a.jsEvent)var l=a.jsEvent={add:function(d,c,f){d.setInterval&&d!=a&&!d.frameElement&&(d=a);f.guid||(f.guid=++m);d.events||(d.events={},d.handle=function(a){b(a);for(var c in d.events[a.type])!1===d.events[a.type][c].call(d,a)&&(a[e](),a[g]())});d.events[c]||(d.events[c]={},d.addEventListener?d.addEventListener(c,d.handle,!1):d.attachEvent?
d.attachEvent("on"+c,d.handle):d["on"+c]=d.handle);d.events[c][f.guid]=f;return l},remove:function(a,b,c){var f=a.events&&a.events[b],g;if(f){delete f[c.guid];for(g in f)return l;a.removeEventListener?a.removeEventListener(b,a.handle,!1):a.detachEvent?a.detachEvent("on"+b,a.handle):a["on"+b]=d;delete a.events[b];for(g in a.events)return l;try{delete a.handle,delete a.events}catch(e){a.removeAttribute("handle"),a.removeAttribute("events")}}return l}}})(e);var y=function(a,f){f&&f.querySelectorAll||
(f=q);return f.querySelectorAll(a)},p=function(a,f){return(f=y(a,f))&&f.length?f[0]:z},v=function(a,f,d){jsEvent.add(a,f,d);return a},r=function(a,f){var d=a.className,b=RegExp("\\b"+f+"\\b","gi");if(d)return b.test(d)?a.className=d.replace(b,""):a.className=d+" "+f,a};(function(a,f){var d=function(a,d){return"padding:"+a+";margin:"+d+";"},b=function(){var a=p("#qrPopupWindowBackground"),b=p("#qrPopupWindowContent");a||(a=f.createElement("div"),a.id="qrPopupWindowBackground",a.setAttribute("style",
"display:none;"),a.onclick=function(){this.style.display="none";return!1},a.title="Нажмите для закрытия",f.body.appendChild(a));b||(b=f.createElement("div"),b.id="qrPopupWindowContent",b.setAttribute("style","width:auto;"+d("8px","0 auto")+"background:#FFF;z-index:65534;-webkit-border-radius:8px;border-radius:8px;-webkit-box-shadow:0 0 10px 0 #000;box-shadow:0 0 10px 0 #000;"),a.appendChild(b));return[a,b]},c=function(a){return'<img src="'+a+'" border="0" style="'+d(0,0)+'" align="middle">'},e=function(a){var d=
b()[1];d.innerHTML=c("http://s.4pda.to/Kkk3MEIwcPpdYQ2NCFz165rIAK1Vqp7EoXTkko4kyC6.gif");d.innerHTML=c("http://qrfree.kaywa.com/?l=1&s=8&d="+encodeURIComponent(a));b()[0].setAttribute("style","position:fixed;left:0;top:0;right:0;bottom:0;display:-webkit-flex;display:-ms-flex:display:none;background:rgba(0,0,0,.5);-ms-flex-align:center;-webkit-align-items:center;align-items:center;z-index:65533")};a.jsShowQr=e;a.jsParseQrForum=function(){for(var b=y('.borderwrap .postcolor a:not([data-qr="false"])'),c=0,h,m,l,k;c<
b.length;c++)(m=(h=b[c]).getAttribute("href"))&&""!=m&&"#"!=m.substr(0,1)&&"java"!=m.substr(0,4)&&(l=f.createElement("img"),l.alt=l.title="QR",l.setAttribute("style","border:0;vertical-align:middle;"+d(0,"0 3px")+"cursor:pointer"),l.src="http://s.4pda.to/Kkk3MEIwcPpdYQ2NCFz165rIAK1Vqp7EoXTkko4kyC6.gif",k=m.split(":")[0],"http"!=k&&"https"!=k&&"market"!=k&&"magnet"!=k&&(k=a.location.pathname,k="/"==m.substr(0,1)?"":-1==k.lastIndexOf("/")?"/":k.substr(0,k.lastIndexOf("/")+1),m=a.location.protocol+"//"+a.location.host+
k+m),l.H=m,l.onclick=function(){e(this.H);return!1},h.parentNode.insertBefore(l,h))}})(e,q);(function(a,f){c_post_block="post-block";c_block_title="block-title";c_open="open";c_close="close";c_box="box";c_unbox="unbox";c_quote="quote";c_hidden="hidden";hasClass=function(a,b){return a.className&&-1<(" "+a.className+" ").indexOf(" "+b+" ")};cl_enable=1;b_touch=!1;fn_ev=function(a){if(!a.isDefaultPrevented()){a=a.target;for(var b,c;a&&a!=f&&!hasClass(a,c_block_title);)a=a.parentNode;if(a&&a!=f&&(b=a.parentNode)&&
hasClass(a,c_block_title)&&hasClass(b,c_post_block)&&cl_enable){cl_enable=0;setTimeout(function(){cl_enable=1},300);if(hasClass(b,c_open)||hasClass(b,c_close)){r(r(b,c_close),c_open);if(hasClass(b,c_open))for(a=b.querySelectorAll("img[data-src]"),c=0;c<a.length;c++)(b=a[c].getAttribute("data-src"))&&b!=a[c].src&&(a[c].src=b);return!1}if(hasClass(b,c_unbox)||hasClass(b,c_box))return r(r(b,c_unbox),c_box),!1}}};v(f,"click",fn_ev);v(f,"touchstart",function(a){if(a.isDefaultPrevented()||b_touch||1!=a.touches.length)b_touch=
!1;else{for(var b=a.target,c;b&&b!=f&&!hasClass(b,c_block_title);)b=b.parentNode;b&&b!=f&&(c=b.parentNode)&&hasClass(b,c_block_title)&&hasClass(c,c_post_block)&&cl_enable&&(b_touch={t:a.touches[0],e:a.target},setTimeout(function(){b_touch=!1},300))}});v(f,"touchend",function(a){if(a.isDefaultPrevented()||!b_touch||1!=a.changedTouches.length&&1!=a.touches.length||a.target!=b_touch.e)b_touch=!1;else{var b=a.changedTouches[0]||a.touches[0],c=Math.sqrt(b_touch.t.screenY-b_touch.t.screenX^2)+(b.screenY-
b.screenX^2);a=a.target;c>(b_touch.t.radiusX+b_touch.t.radiusY)/2+(b.radiusX+b.radiusY)/2&&(a.fireEvent?a.fireEvent("onclick"):(b=f.createEvent("Events"),b.initEvent("click",!0,!1),a.dispatchEvent(b)))}});a.initPostBlock=function(){var a,b,c,e,g=0;try{a=f.querySelectorAll(".post-block.spoil.close img");for(g=0;g<a.length;g++)c=a[g],c.setAttribute("data-src",c.src),c.src="";a=f.getElementsByName(location.hash.replace(/^#/,""));for(g=0;g<a.length;g++){c=[];e=0;if("A"==a[g].tagName)for(b=a[g].parentNode;b&&
b!=f.body&&!(e=/^post-main-\d+$/.test(b.id));)b=b.parentNode,c.push(b);if(e)for(;c.length;)b=c.pop(),hasClass(b,c_post_block)&&hasClass(b,c_close)&&r(r(b,c_close),c_open)}}catch(p){}a=f.body||f.getElementsByTagName("body")[0];b=f.createElement("style");c=f.createElement("div");g=!1;b.type="text/css";c.className="checkPseudoSupport";b.styleSheet?b.styleSheet.cssText='.checkPseudoSupport{position:fixed;left:-100px;top:-100px;display:block;width:auto;height:auto} .checkPseudoSupport:before{content:"";display:block;height:50px}':
b.appendChild(f.createTextNode('.checkPseudoSupport{position:fixed;left:-100px;top:-100px;display:block;width:auto;height:auto} .checkPseudoSupport:before{content:"";display:block;height:50px}'));a.appendChild(b);a.appendChild(c);g=40<c.offsetHeight;a.removeChild(c);a.removeChild(b);if(!g){var h,m="BLOCK";a=y("."+c_post_block+">."+c_block_title);for(g=0;g<a.length;g++)h=0,b=(c=a[g]).parentNode,e=!(c.innerHTML+"").replace(/(^\s+)|(\s+$)/g,""),hasClass(b,c_close)||hasClass(b,c_open)?(m="SPOILER",h=
1):hasClass(b,c_box)||hasClass(b,c_unbox)?(m="CODE",h=1):hasClass(b,c_quote)?m="QUOTE":hasClass(b,c_hidden)&&(m="HIDE"),e&&(c.innerHTML=m),h&&v(a[g],"click",fn_ev)}}})(e,q);(function(a,f){setTimeout(function(d,b,c,f){"CONFIG"in a&&"tz"in a.CONFIG&&"baseurl"in a.CONFIG&&(d=new Date,b=-parseInt(d.getTimezoneOffset()/30),c=a.CONFIG.baseurl+"act=xmlout&do=tz-autoset&tz="+30*b,b!=2*parseFloat(a.CONFIG.tz)&&((f=function(a){try{return new XMLHttpRequest}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(d){}try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(c){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(f){}return 0}())?
(f.onreadystatechange=function(){4==this.readyState&&"success"!=this.responseText&&(a.location=c)},f.open("GET",c+"&xml=1&_="+d.getTime()),f.send(null)):a.location=c))},1E3)})(e);(function(){function a(a,b){return a.getAttribute("data-"+b)}function f(a){var b=p('.borderwrap[data-post="'+a+'"]');b||(b=p('.borderwrap .ipbtable[data-post="'+a+'"]'))||(b=p('#ipbwrapper [data-post="'+a+'"]'));return b}function d(){n=ipb_var_base_url;var b=n+"act=zmod&auth_key="+ipb_md5_check+"&",d=q.getElementById("se-mod-frm"),
k='<img src="'+c+'" alt="Закрепить пост" />',h='<img src="'+r+'" alt="Открепить пост" />',x=function(){alert("Ошибка на сервере")};d&&(d.setAttribute("method","POST"),d.setAttribute("action",b+"&st="+ipb_var_st));e["--seMODpin"]=function(d,c,g){c=c||e.event;c.preventDefault&&c.preventDefault();c.returnValue=!1;var l=a(d,"pin");confirm("Вы действительно хотите "+("pinpost"==l?"поднять":"опустить")+" данный пост?")&&(c=new w,c.show_loading(),c.done(function(b){if("ok"!=b.responseText)alert("Ошибка");
else{"pinpost"==l?(d.innerHTML=h,d.setAttribute("data-pin","unpinpost")):(d.innerHTML=k,d.setAttribute("data-pin","pinpost"));b=p("#topic-pin-content");var c=f(g),e,m=0;!b&&(e=p("#ipbwrapper > .borderwrap > .maintitle:first-child > table"))&&(e=e.parentNode,b=q.createElement("div"),b.id="topic-pin-content",e.parentNode.insertBefore(b,e.nextSibling));if(c&&b&&"pinpost"==l){try{m=a(p("[data-post]:first-child",b),"post")}catch(A){}if(e=f(m)){c.parentNode.insertBefore(e,c.nextSibling);try{e=p('.pinlink[data-pin="unpinpost"]',
e),e.setAttribute("data-pin","pinpost"),e.innerHTML=k}catch(B){}}b.appendChild(c)}}}).fail(x).complete(c.hide_loading),c.process(b+"p="+g+"&code="+a(d,"pin")))};e["--seMODhide"]=function(d,c,k){c=c||e.event;c.preventDefault&&c.preventDefault();c.returnValue=!1;var l=a(d,"approve");c=new w;c.show_loading();c.done(function(a){if("ok"!=a.responseText)alert("Ошибка");else{l="approve"==l?"unapprove":"approve";d.setAttribute("data-approve",l);var b=f(k);b&&(b.className=(b.className+"").replace(/(^|\s+)hidepin(\s+|$)/g,
" ").replace(/^\s+|\s+$/gm,""),"approve"==l?(b.className+=" hidepin",d.innerHTML='<img src="'+g+'" atl="Опубликовать" title="Опубликовать пост"/>'):d.innerHTML='<img src="'+g+'" atl="Скрыть" title="Скрыть пост"/>');if(b=q.getElementById("post-main-"+k)){a="post"+(/(^|\s+)post2/.test(b.className+"")?2:1);for(var c=b,b=b.className,e=a+"shaded2 "+a,b=(b+"").split(" "),e=(e+"").split(" "),m=[],h=0;h<b.length;h++)m.push(-1<e.indexOf(b[h])?"":b[h]);b=m.join(" ").replace(/\s\s+/gm," ");c.className=b+a+("approve"==
l?"shaded2":"")}}}).fail(x).complete(c.hide_loading);c.process(b+"code=postchoice&selectedpids="+k+"&tact="+l)};e["--seMODdel"]=function(a,c,d){c=c||e.event;c.preventDefault&&c.preventDefault();c.returnValue=!1;confirm("Вы действительно хотите удалить это сообщение?")&&(a=new w,a.show_loading(),a.done(function(a){"ok"!=a.responseText?alert("Ошибка"):(a=f(d))&&a.parentNode.removeChild(a)}).fail(x).complete(a.hide_loading),a.process(b+"code=postchoice&tact=delete&selectedpids="+d))}}function b(){var a=
0,b=10,c=[],d,f=function(){("function"==typeof checkdelete||0<b)&&a&&clearInterval(a);b--;if("function"==typeof checkdelete){var c=checkdelete;checkdelete=function(){localStorage.removeItem("modpids-"+e.ipb_input_t);localStorage.removeItem("modtids-"+e.ipb_input_f);return c.apply(this,arguments)}}},g=function(a,b){var c,e=((localStorage.getItem("mod"+a+"-"+parseInt(b))||"")+"").split(","),f=[];for(d=0;d<e.length;d++)e[d]&&(f.push(e[d]),c=p('input[value="'+e[d]+'"][data-field="selected'+a+'"]'))&&
(c.checked=!0);return f},h=function(a,b){if(!parseInt(b)){for(var c=[],d=0,e="mod"+a+"-",f=e.length;d<localStorage.length;d++)(localStorage.key(d)+"").substr(0,f)==e&&c.push(localStorage.key(d));for(d=0;d<c.length;d++)localStorage.removeItem(c[d])}},n=function(a,b){return p('form[name="modform"] [name="CODE"][value="'+a+'"]~[name="'+b+'"]')};try{var q=n("postchoice","selectedpids"),r=n("topicchoice","selectedtids");localStorage&&localStorage.setItem&&(h("pids",e.ipb_input_t),h("tids",e.ipb_input_f),
c=g("pids",e.ipb_input_t),q&&(q.value=c.join(","),p('form[name="modform"] [name="gobutton"]').value=lang_gobutton+" ("+c.length+")"),c=g("tids",e.ipb_input_f),r&&(r.value=c.join(","),p('form[name="modform"] [name="gobutton"]').value=lang_gobutton+" ("+c.length+")"),a=setInterval(f,500))}catch(s){}}var c="http://s.4pda.to/Kkk3TjkZ6hYo8wol2WVKYiTEKBhWACuBRJqAnVD.gif",r="http://s.4pda.to/Kkk3TjkZtSyz0VVBWuz0ZJ4sqL49hcUApt8QYm1QT2FW.gif",g="http://s.4pda.to/Kkk346WUCmqRQWsIwl3poocvS6qTWtS6Fn0XELE6.gif",n="?";e.ipb||(e.ipb={});e.ipb.frmChkToggle=
function(b,c){if(b){var d=p(a(b,"form")),f=p('[name="'+a(b,"field")+'"]',d),g=b.value+"",h=b.checked?1:0,n=a(b,"lskey"),q=a(b,"var");if(d&&f){var n=n?n+"":!1,q=q&&e[q]?q:!1,r=(f.value+"").split(","),u=[],s;for(s=0;s<r.length;s++)r[s]&&r[s]!=g&&u.push(r[s]);h&&u.push(g);try{"undefined"!=typeof lang_gobutton&&(h=p('[name="gobutton"]',d))&&(h.value=lang_gobutton+" ("+u.length+")"),q&&n&&localStorage.setItem&&localStorage.setItem(n+"-"+e[q],u.join(","))}catch(t){}f.value=u.join(",")}else c=c||e.event,
c.preventDefault&&c.preventDefault(),c.returnValue=!1}else c=c||e.event,c.preventDefault&&c.preventDefault(),c.returnValue=!1};var h=0,h=setInterval(function(){/int|com/.test(q.readyState)&&(h&&clearInterval(h),d(),b())},300)})()})(window,document);
